/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formDialogs;

import database.Database;
import javax.swing.JOptionPane;
import models.MataPelajaran;

/**
 *
 * @author iqbal
 */
public class frmUpdateMapel extends javax.swing.JDialog {

    /**
     * Creates new form frmUpdateMapel
     */
    public frmUpdateMapel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtNoMapel.setEditable(false);
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(96, 96, 96));
    }
    
     public void setForm(MataPelajaran mapel) {
        txtNoMapel.setText(mapel.getNoMapel());
        txtNamaMapel.setText(mapel.getNamaMapel());
        txtJumlahJam.setText(String.valueOf(mapel.getJumlahJam()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNoMapel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNamaMapel = new javax.swing.JTextField();
        txtJumlahJam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tblEdit = new javax.swing.JButton();
        tblBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Update Data Mata Pelajaran");

        txtNoMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoMapelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No Mapel");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Mapel");

        txtNamaMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMapelActionPerformed(evt);
            }
        });

        txtJumlahJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahJamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Jam");

        tblEdit.setBackground(new java.awt.Color(51, 204, 0));
        tblEdit.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        tblEdit.setText("Edit");
        tblEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblEditActionPerformed(evt);
            }
        });

        tblBatal.setBackground(new java.awt.Color(255, 51, 0));
        tblBatal.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        tblBatal.setText("Batal");
        tblBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addComponent(txtJumlahJam, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNoMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNamaMapel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(tblEdit)
                .addGap(61, 61, 61)
                .addComponent(tblBatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJumlahJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblBatal)
                    .addComponent(tblEdit))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoMapelActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNoMapelActionPerformed

    private void txtJumlahJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahJamActionPerformed

    private void tblEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblEditActionPerformed
        // TODO add your handling code here:

         //validasi
        boolean isValidate = true;
        
        if(txtNamaMapel.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null
                ,"Nama Mata Pelajaran harus diisi",
                "Error!",
                JOptionPane.ERROR_MESSAGE);
            isValidate = false;
        }

        if(txtNamaMapel.getText().trim().length() < 5) {
            JOptionPane.showMessageDialog(null
                ,"Nama Mata pelajaran harus lebih dari 5 karakter",
                "Error!",
                JOptionPane.ERROR_MESSAGE);
            isValidate = false;
        }
        
        if(txtJumlahJam.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null
                ,"Jumlah jam harus diisi",
                "Error!",
                JOptionPane.ERROR_MESSAGE);
            isValidate = false;
        }
        
        String jumlahJamRegex = "^\\d*\\.\\d+|\\d+\\.?\\d*$";
        if(!txtJumlahJam.getText().matches(jumlahJamRegex) ) {
            JOptionPane.showMessageDialog(null
                ,"Jumlah Jam harus angka!!",
                "Error!",
                JOptionPane.ERROR_MESSAGE);
            isValidate = false;
        }
        
        if (isValidate == true) {
            Database db = new Database();
            db.updateMapel(new MataPelajaran(
                txtNoMapel.getText(),
                txtNamaMapel.getText(),
                Double.parseDouble(txtJumlahJam.getText())
            ));
            JOptionPane.showMessageDialog(null
              ,"Data Berhasil diedit!!!");
            setVisible(false);
        } else {
             JOptionPane.showMessageDialog(null
              ,"Data Gagal diedit!!!");
            isValidate = false;
            setVisible(false);
        }
    }//GEN-LAST:event_tblEditActionPerformed

    private void tblBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBatalActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_tblBatalActionPerformed

    private void txtNamaMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMapelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUpdateMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUpdateMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUpdateMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUpdateMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmUpdateMapel dialog = new frmUpdateMapel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JButton tblBatal;
    public javax.swing.JButton tblEdit;
    public javax.swing.JTextField txtJumlahJam;
    public javax.swing.JTextField txtNamaMapel;
    public javax.swing.JTextField txtNoMapel;
    // End of variables declaration//GEN-END:variables
}
